project:
  type: website
  post-render:
    - "cp -rnv static/images/. _site/static/img"
    - "cp sw.js _site/"
  preview:
    # host: 0.0.0.0
    port: 4200
    browser: false


website:
  title: "Rede de Educação e Saúde"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Página inicial
      - href: municipio.qmd
        text: Dados
      - sobre.qmd
      
    right: 
      - icon: instagram
        href: https://instagram.com/rede_de_educacao_e_saude_

format:
  html:
    echo: false
    theme: minty
    css: styles.css
    toc: true



