project:
  type: website
  post-render:
    - "cp -rnv static/images/. _site/static/img"
    - "cp sw.js _site/"
  preview:
    # host: 0.0.0.0
    port: 4200
    browser: false


website:
  title: "Rede de Educação e Saúde"
  search: false
  navbar:

      
      
    right:
        # Substituir no futuro com as respectivas páginas
      - href: http://localhost:4200/proeficiencia/
        text: Proeficiência
      - text: Publicações
        menu: 
          - href: http://localhost:4200/publicacoes_gerais/
            text: Publicações Gerais
          - href: http://localhost:4200/artigos/
            text: Artigos
      - text: Cursos de Formação
        menu: 
          - href: http://localhost:4200/curso_especializacao/
            text: Curso de especialização
          - href: http://localhost:4200/jovem_doutor/
            text: Jovem Doutor
      - sobre.qmd 
      - icon: instagram
        href: https://instagram.com/rede_de_educacao_e_saude_

format:
  html:
    toc: false
    echo: false
    keep-hidden: true
    smooth-scroll: true
    theme: 
      - minty
      - custom.scss
    css: styles.css
    page-layout: custom
    
    
    
    



