project:
  type: website
  post-render:
    - quarto run files/scripts/copy_files_site.ts
  preview:
    # host: 0.0.0.0
    port: 4200
    browser: false


website:
  title: "Rede de Educação e Saúde"
  search: false
  navbar:
    right:
        # Substituir no futuro com as respectivas páginas
      - href: ./proeficiencia/
        text: Proeficiência
      - text: Publicações
        menu: 
          - href: ./publicacoes_gerais/
            text: Publicações Gerais
          - href: ./artigos/
            text: Artigos
      - text: Cursos de Formação
        menu: 
          - href: ./curso_especializacao/
            text: Curso de especialização
          - href: ./jovem_doutor/
            text: Jovem Doutor
      - href: sobre.qmd
        text: Sobre 
      - icon: instagram
        href: https://instagram.com/rede_de_educacao_e_saude_
      - icon: youtube
        href: https://www.youtube.com/@RedeEducacaoeSaudeemEscolasPub
      - icon: github
        href: https://github.com/resepemb/rede-educacao-e-saude
  page-footer:
    background: "darkcyan"
    foreground: "#ffffff"
    border: false
    left:
      - text: Página inicial
        href: index.qmd
      - text: Sobre
        href: sobre.qmd
    center:
      - text: "Versão: {{< env TAG_NAME >}}"
    right:
      - text: "Realização:"
      - icon: gov 
        href: https://www.gov.br/cnpq/pt-br
      - icon: ufrb
        href: https://www.ufrb.edu.br
      - icon: ifba
        href: https://portal.ifba.edu.br/

format:
  html:
    toc: false
    echo: false
    keep-hidden: true
    smooth-scroll: true
    theme: 
      - minty
      - custom.scss
    css: styles.css
    page-layout: custom
    
    
